version: '3'

services:

  cyban:
    build:
      context: .
      dockerfile: Dockerfile_CyBan
    image: cyban
    container_name: cyban
    depends_on:
      - mongo
      - nginx
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://cyban-admin:cyban-admin-password@mongo:27017/?authSource=admin
    env_file:
      - ./.env

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx-cfg/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-cfg/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
    
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cyban-admin
      - MONGO_INITDB_ROOT_PASSWORD=cyban-admin-password
    volumes:
      - mongo:/data/db
    command: --quiet --logpath /dev/null
    logging:
      driver: none

volumes:
  mongo: